import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.benefits': 'Why Us',
    'nav.coverage': 'Coverage',
    'nav.contact': 'Contact',
    'header.callNow': 'Call Now',
    
    // Hero
    'hero.title': 'PROTECT YOUR HOME FROM HURRICANES',
    'hero.subtitle': 'Professional installation of impact windows and doors across the United States. Maximum protection, superior quality.',
    'hero.ownerQuote': "I'm Abelardo Soler, with over 8 years of experience installing impact doors and windows across the United States. We have the expertise to transform your home safely and professionally.",
    'hero.ownerName': 'Abelardo Soler',
    'hero.ownerTitle': 'Founder & Lead Installer',
    'hero.cta.call': 'Call Now',
    'hero.cta.estimate': 'Get Free Estimate',
    'hero.cta.doorDesigns': 'Door Designs',
    'hero.cta.comingSoon': 'Coming Soon',
    'hero.cta.projects': 'Our Projects',
    
    // Services
    'services.title': 'OUR SERVICES',
    'services.subtitle': 'Complete hurricane protection solutions for your home and business',
    'services.windows.title': 'Impact Windows',
    'services.windows.desc': 'Hurricane-resistant windows that protect your home while maintaining natural light and energy efficiency.',
    'services.doors.title': 'Impact Doors',
    'services.doors.desc': 'Reinforced entry doors designed to withstand extreme weather conditions and provide maximum security.',
    'services.hurricane.title': 'Hurricane Protection',
    'services.hurricane.desc': 'Complete storm protection systems including shutters, panels, and reinforcement solutions.',
    'services.installation.title': 'Professional Installation',
    'services.installation.desc': 'Expert installation by certified technicians ensuring proper fit and optimal performance.',
    
    // Benefits
    'benefits.title': 'WHY CHOOSE US',
    'benefits.subtitle': "I'm tired of seeing less experienced installers deliver poor work. Impact window installation is a premium service — and the quality should match. That's what sets us apart. I didn't start yesterday; I've been doing this for years, and our clients' satisfaction is always the priority.",
    'benefits.experience.title': 'Years of Experience',
    'benefits.experience.desc': 'Decades of expertise in hurricane protection installations.',
    'benefits.quality.title': 'Premium Quality',
    'benefits.quality.desc': 'Only the highest quality materials and products.',
    'benefits.nationwide.title': 'Nationwide Service',
    'benefits.nationwide.desc': 'Serving all 50 states across the United States.',
    'benefits.warranty.title': 'Full Warranty',
    'benefits.warranty.desc': 'Comprehensive warranty on all installations.',
    'benefits.certified.title': 'Certified Technicians',
    'benefits.certified.desc': 'Factory-trained and certified installation teams.',
    'benefits.support.title': '24/7 Support',
    'benefits.support.desc': 'Round-the-clock customer service and support.',
    
    // Coverage
    'coverage.title': 'NATIONWIDE COVERAGE',
    'coverage.subtitle': 'Serving all 50 states',
    'coverage.desc': 'From coast to coast, we provide professional hurricane protection services. No matter where you are in the United States, our expert team is ready to protect your home.',
    'coverage.cta': 'Check Availability',
    
    // Footer
    'footer.owner': 'Owner',
    'footer.tagline': 'Your trusted partner in hurricane protection',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'footer.callUs': 'Call Us',
    
    // Calculator
    'calc.title': 'Estimate Calculator',
    'calc.subtitle': 'Configure your MrGlass impact windows and doors',
    'calc.selectProduct': 'Select Product',
    'calc.configure': 'Configure',
    'calc.summary': 'Summary',
    'calc.windows': 'Impact Windows',
    'calc.doors': 'Impact Doors',
    
    // MrGlass Window Types
    'calc.MG200_SH': 'Single Hung Window',
    'calc.MG300_HR': 'Horizontal Roller Window',
    'calc.MG400_PW': 'Picture Window',
    'calc.MG450_PW': 'Picture Window Premium',
    'calc.MG600_CA': 'Casement/Awning Window',
    
    // MrGlass Door Types
    'calc.MG1000_SGD': 'Sliding Glass Door',
    'calc.MG1100_SGD': 'SGD MultiTrack',
    'calc.MG1500_SGD': 'Sliding Glass Door Premium',
    'calc.MG3000_FD': 'French Door',
    
    // Configuration
    'calc.quantity': 'Quantity',
    'calc.width': 'Width (inches)',
    'calc.height': 'Height (inches)',
    'calc.frameColor': 'Frame Color',
    'calc.windZone': 'Wind Zone',
    'calc.glassTint': 'Glass Tint',
    'calc.glassType': 'Glass Type',
    'calc.area': 'Area',
    'calc.lowE': 'Low-E Coating',
    'calc.privacy': 'Privacy Glass',
    'calc.configuration': 'Configuration',
    'calc.screen': 'Screen',
    
    // Frame Colors (simplified)
    'calc.white_2605': 'White',
    'calc.gray_2605': 'Gray',
    'calc.black_matte': 'Black',
    'calc.bronze_2605': 'Bronze',
    
    // Glass Types
    'calc.clear_laminated': 'Laminated Glass',
    'calc.insulated_laminated': 'Insulated Laminated Glass',
    
    // Reset button
    'calc.reset': 'Reset',
    
    // Glass Tint Categories
    'calc.tintBasic': 'Basic',
    'calc.tintGreen': 'Green Tones',
    'calc.tintBlue': 'Blue Tones',
    'calc.tintSpecial': 'Special',
    
    // Glass Tints
    'calc.clear': 'Clear',
    'calc.gray': 'Gray',
    'calc.bronze_tint': 'Bronze',
    'calc.solex_green': 'Solex Green',
    'calc.blue_green': 'Blue-Green',
    'calc.azuria': 'Azuria',
    'calc.solar_blue': 'Solar Blue',
    'calc.artic_blue': 'Artic Blue',
    'calc.pacific_blue': 'Pacific Blue',
    'calc.pacifica_blue': 'Pacifica Blue',
    'calc.solar_cool_gray': 'Solar Cool Gray',
    'calc.solar_cool_bronze': 'Solar Cool Bronze',
    'calc.double_gray': 'Double Gray',
    'calc.double_bronze': 'Double Bronze',
    'calc.gray_lite_ii': 'Gray Lite II',
    'calc.solarcool_azuria': 'Solarcool Azuria',
    'calc.solarcool_pacifica': 'Solarcool Pacifica',
    
    // Low-E Options
    'calc.none': 'None',
    'calc.clima_guard_62_27': 'Clima Guard 62/27',
    'calc.sb70': 'SB70',
    'calc.sb60': 'SB60',
    
    // Actions
    'calc.yes': 'Yes',
    'calc.no': 'No',
    'calc.addProduct': 'Add Product',
    'calc.yourProducts': 'Your Products',
    'calc.noProducts': 'No products added yet',
    'calc.remove': 'Remove',
    'calc.estimatedTotal': 'Estimated Total',
    'calc.priceRange': 'Estimated Price Range',
    'calc.disclaimer': 'This is an approximate estimate based on standard configurations. Final price may vary depending on availability, current promotions, and exact specifications. Call us for an official quote at no obligation.',
    'calc.callForFinal': 'Call for Official Quote',
    'calc.startOver': 'Start Over',
    'calc.close': 'Close',
    'calc.next': 'Next',
    'calc.back': 'Back',
    'calc.sqft': 'sq ft',
    'calc.each': 'each',
    'calc.saveEstimate': 'Save Estimate',
    
    // Save Estimate Modal
    'estimate.saveTitle': 'Save Your Estimate',
    'estimate.savedTitle': 'Estimate Saved!',
    'estimate.saveDesc': 'Enter your information to save your estimate and receive a personalized quote.',
    'estimate.fullName': 'Full Name',
    'estimate.fullNamePlaceholder': 'John Doe',
    'estimate.email': 'Email',
    'estimate.emailPlaceholder': 'your@email.com',
    'estimate.phone': 'Phone (optional)',
    'estimate.phonePlaceholder': '+1 555 123 4567',
    'estimate.yourEstimate': 'Your Estimate',
    'estimate.products': 'products',
    'estimate.cancel': 'Cancel',
    'estimate.save': 'Save & Send',
    'estimate.savedMessage': 'Your estimate has been saved!',
    'estimate.savedSubtitle': 'We will contact you soon. You can also reach us directly:',
    'estimate.sendWhatsApp': 'Send via WhatsApp',
    'estimate.callNow': 'Call Now',
    'estimate.success.title': 'Estimate Saved!',
    'estimate.success.desc': 'We\'ll contact you soon with your personalized quote.',
    'estimate.error.title': 'Error',
    'estimate.error.desc': 'Could not save estimate. Please try again.',
    'estimate.error.invalidEmail': 'Please enter a valid email.',
    'estimate.error.invalidPhone': 'Please enter a valid phone number.',
    
    // Auth
    'auth.loginTitle': 'Admin Login',
    'auth.loginSubtitle': 'Sign in to access the admin panel',
    'auth.signupTitle': 'Create Account',
    'auth.signupSubtitle': 'Register to access admin features',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.fullName': 'Full Name',
    'auth.fullNamePlaceholder': 'John Doe',
    'auth.loginButton': 'Sign In',
    'auth.signupButton': 'Create Account',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.signupLink': 'Sign up',
    'auth.loginLink': 'Sign in',
    'auth.backHome': 'Back to Home',
    'auth.error.title': 'Error',
    'auth.error.generic': 'An error occurred. Please try again.',
    'auth.error.invalidCredentials': 'Invalid email or password.',
    'auth.error.emailNotConfirmed': 'Please confirm your email before signing in.',
    'auth.error.alreadyRegistered': 'This email is already registered.',
    'auth.success.loginTitle': 'Welcome!',
    'auth.success.loginDesc': 'You have successfully signed in.',
    'auth.success.signupTitle': 'Account Created!',
    'auth.success.signupDesc': 'Your account has been created. You can now sign in.',
    
    // Admin
    'admin.title': 'Admin Panel',
    'admin.logout': 'Sign Out',
    'admin.welcome': 'Welcome to the Admin Panel',
    'admin.welcomeDesc': 'Manage your leads, view estimates, and track your business.',
    'admin.quickActions': 'Quick Actions',
    'admin.dashboard': 'Dashboard',
    'admin.dashboardDesc': 'View statistics and metrics',
    'admin.leads': 'Leads',
    'admin.leadsDesc': 'Manage customer contacts',
    'admin.estimates': 'Estimates',
    'admin.estimatesDesc': 'View submitted estimates',
    'admin.comingSoon': 'Coming Soon',
    'admin.note': 'Note',
    'admin.noteDesc': 'The CRM features are being developed. Check back soon for lead management and estimate tracking.',
    'admin.home': 'Home',
    'admin.soon': 'Soon',
    'footer.adminLogin': 'Admin',
    
    // CRM
    'crm.leadsTitle': 'Lead Management',
    'crm.leadsSubtitle': 'View and manage all your customer leads',
    'crm.refresh': 'Refresh',
    'crm.searchPlaceholder': 'Search by name, email or phone...',
    'crm.loading': 'Loading leads...',
    'crm.noLeads': 'No leads yet',
    'crm.noLeadsDesc': 'Leads will appear here when customers submit their information.',
    'crm.noResults': 'No results found',
    'crm.noResultsDesc': 'Try adjusting your search or filter criteria.',
    'crm.call': 'Call',
    'crm.showMore': 'Show more options',
    'crm.showLess': 'Show less',
    'crm.changeStatus': 'Change Status',
    'crm.addNotes': 'Add Notes',
    'crm.editNotes': 'Edit Notes',
    'crm.linkedEstimates': 'Linked Estimates',
    'crm.products': 'products',
    'crm.view': 'View',
    'crm.source': 'Source',
    'crm.notesFor': 'Notes for',
    'crm.notesPlaceholder': 'Add notes about this lead... (e.g., conversation details, follow-up reminders, special requests)',
    'crm.notesHint': 'Notes are private and only visible to admins.',
    'crm.cancel': 'Cancel',
    'crm.saveNotes': 'Save Notes',
    'crm.filter.all': 'All',
    'crm.filter.new': 'New',
    'crm.filter.contacted': 'Contacted',
    'crm.filter.negotiating': 'Negotiating',
    'crm.filter.won': 'Won',
    'crm.filter.lost': 'Lost',
    'crm.status.new': 'New',
    'crm.status.contacted': 'Contacted',
    'crm.status.negotiating': 'Negotiating',
    'crm.status.won': 'Won',
    'crm.status.lost': 'Lost',
    'crm.error.fetchTitle': 'Error loading leads',
    'crm.error.fetchDesc': 'Could not load leads. Please try again.',
    'crm.error.updateTitle': 'Error updating',
    'crm.error.updateDesc': 'Could not save changes. Please try again.',
    'crm.success.statusTitle': 'Status updated',
    'crm.success.statusDesc': 'Lead status has been changed.',
    'crm.success.notesTitle': 'Notes saved',
    'crm.success.notesDesc': 'Your notes have been saved.',
    
    // Lead Capture
    'lead.title': 'GET A FREE ESTIMATE',
    'lead.subtitle': 'Enter your email and we\'ll contact you with a personalized quote for your project.',
    'lead.emailPlaceholder': 'Enter your email',
    'lead.submit': 'Get Quote',
    'lead.sent': 'Sent!',
    'lead.success.title': 'Request Received!',
    'lead.success.desc': 'We\'ll contact you soon with your estimate.',
    'lead.success.message': 'Thank you! We\'ll be in touch shortly.',
    'lead.error.invalidEmail': 'Please enter a valid email address.',
    'lead.error.duplicate': 'This email is already registered. We\'ll contact you soon!',
    'lead.error.generic': 'Something went wrong. Please try again.',
    'lead.privacy': 'We respect your privacy. No spam, ever.',
    
    // WhatsApp Button
    'whatsapp.button': 'Chat with Us',
    'whatsapp.aria': 'Contact us via WhatsApp',
    'whatsapp.defaultMessage': 'Hi! I\'m interested in impact windows and doors. Can you help me?',
    
    // Dashboard
    'dashboard.totalLeads': 'Total Leads',
    'dashboard.estimates': 'Estimates',
    'dashboard.wonDeals': 'Won Deals',
    'dashboard.conversion': 'Conversion',
    'dashboard.leadsByStatus': 'Leads by Status',
    'dashboard.totalRevenue': 'Total Revenue',
    'dashboard.revenueDesc': 'Sum of all submitted estimates',
    'dashboard.recentLeads': 'Recent Leads',
    
    // Estimates List
    'estimates.title': 'Estimates',
    'estimates.subtitle': 'View all submitted estimates',
    'estimates.searchPlaceholder': 'Search by name or email...',
    'estimates.noEstimates': 'No estimates yet',
    'estimates.noEstimatesDesc': 'Estimates will appear here when customers submit them.',
    'estimates.anonymous': 'Anonymous',
    'estimates.taxIncluded': 'Tax included',
    'estimates.contactInfo': 'Contact Information',
    'estimates.product': 'Product',
    'estimates.dimensions': 'Dimensions',
    'estimates.options': 'Options',
    'estimates.price': 'Price',
    'estimates.subtotal': 'Subtotal',
    'estimates.taxes': 'Taxes',
    'estimates.total': 'Total',
    'estimates.exportPDF': 'Export PDF',
  },
  es: {
    // Header
    'nav.home': 'Inicio',
    'nav.services': 'Servicios',
    'nav.benefits': 'Por Qué Nosotros',
    'nav.coverage': 'Cobertura',
    'nav.contact': 'Contacto',
    'header.callNow': 'Llamar Ahora',
    
    // Hero
    'hero.title': 'PROTEGE TU HOGAR DE LOS HURACANES',
    'hero.subtitle': 'Instalación profesional de ventanas y puertas contra impacto en todo Estados Unidos. Máxima protección, calidad superior.',
    'hero.ownerQuote': 'Soy Abelardo Soler, con más de 8 años de experiencia instalando puertas y ventanas de impacto en todo Estados Unidos. Contamos con la experiencia para transformar tu hogar de manera segura y profesional.',
    'hero.ownerName': 'Abelardo Soler',
    'hero.ownerTitle': 'Fundador e Instalador Principal',
    'hero.cta.call': 'Llamar Ahora',
    'hero.cta.estimate': 'Obtener Estimado Gratis',
    'hero.cta.doorDesigns': 'Diseños de Puertas',
    'hero.cta.comingSoon': 'Próximamente',
    'hero.cta.projects': 'Nuestros Proyectos',
    
    // Services
    'services.title': 'NUESTROS SERVICIOS',
    'services.subtitle': 'Soluciones completas de protección contra huracanes para tu hogar y negocio',
    'services.windows.title': 'Ventanas de Impacto',
    'services.windows.desc': 'Ventanas resistentes a huracanes que protegen tu hogar mientras mantienen la luz natural y eficiencia energética.',
    'services.doors.title': 'Puertas de Impacto',
    'services.doors.desc': 'Puertas de entrada reforzadas diseñadas para resistir condiciones climáticas extremas y brindar máxima seguridad.',
    'services.hurricane.title': 'Protección contra Huracanes',
    'services.hurricane.desc': 'Sistemas completos de protección contra tormentas incluyendo persianas, paneles y soluciones de refuerzo.',
    'services.installation.title': 'Instalación Profesional',
    'services.installation.desc': 'Instalación experta por técnicos certificados asegurando ajuste apropiado y rendimiento óptimo.',
    
    // Benefits
    'benefits.title': 'POR QUÉ ELEGIRNOS',
    'benefits.subtitle': 'Estoy cansado de ver cómo instaladores con menos experiencia hacen trabajos pésimos. La instalación de ventanas de impacto es un servicio costoso y la calidad debe estar a la altura. Eso es lo que nos diferencia: no comencé ayer, llevo años en esto y la satisfacción de nuestros clientes es siempre la prioridad.',
    'benefits.experience.title': 'Años de Experiencia',
    'benefits.experience.desc': 'Décadas de experiencia en instalaciones de protección contra huracanes.',
    'benefits.quality.title': 'Calidad Premium',
    'benefits.quality.desc': 'Solo materiales y productos de la más alta calidad.',
    'benefits.nationwide.title': 'Servicio Nacional',
    'benefits.nationwide.desc': 'Servimos los 50 estados de Estados Unidos.',
    'benefits.warranty.title': 'Garantía Completa',
    'benefits.warranty.desc': 'Garantía integral en todas las instalaciones.',
    'benefits.certified.title': 'Técnicos Certificados',
    'benefits.certified.desc': 'Equipos de instalación entrenados y certificados de fábrica.',
    'benefits.support.title': 'Soporte 24/7',
    'benefits.support.desc': 'Servicio al cliente y soporte las 24 horas.',
    
    // Coverage
    'coverage.title': 'COBERTURA NACIONAL',
    'coverage.subtitle': 'Sirviendo los 50 estados',
    'coverage.desc': 'De costa a costa, brindamos servicios profesionales de protección contra huracanes. Sin importar dónde estés en Estados Unidos, nuestro equipo experto está listo para proteger tu hogar.',
    'coverage.cta': 'Verificar Disponibilidad',
    
    // Footer
    'footer.owner': 'Propietario',
    'footer.tagline': 'Tu socio de confianza en protección contra huracanes',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.contact': 'Contacto',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.callUs': 'Llámanos',
    
    // Calculator
    'calc.title': 'Calculadora de Estimados',
    'calc.subtitle': 'Configura tus ventanas y puertas de impacto MrGlass',
    'calc.selectProduct': 'Seleccionar Producto',
    'calc.configure': 'Configurar',
    'calc.summary': 'Resumen',
    'calc.windows': 'Ventanas de Impacto',
    'calc.doors': 'Puertas de Impacto',
    
    // MrGlass Window Types
    'calc.MG200_SH': 'Ventana Single Hung',
    'calc.MG300_HR': 'Ventana Deslizante Horizontal',
    'calc.MG400_PW': 'Ventana Panorámica',
    'calc.MG450_PW': 'Ventana Panorámica Premium',
    'calc.MG600_CA': 'Ventana Abatible/Proyectante',
    
    // MrGlass Door Types
    'calc.MG1000_SGD': 'Puerta Corredera de Cristal',
    'calc.MG1100_SGD': 'Puerta Corredera MultiTrack',
    'calc.MG1500_SGD': 'Puerta Corredera Premium',
    'calc.MG3000_FD': 'Puerta Francesa',
    
    // Configuration
    'calc.quantity': 'Cantidad',
    'calc.width': 'Ancho (pulgadas)',
    'calc.height': 'Alto (pulgadas)',
    'calc.frameColor': 'Color del Marco',
    'calc.windZone': 'Zona de Viento',
    'calc.glassTint': 'Tinte del Cristal',
    'calc.glassType': 'Tipo de Vidrio',
    'calc.area': 'Área',
    'calc.lowE': 'Recubrimiento Low-E',
    'calc.privacy': 'Cristal con Privacidad',
    'calc.configuration': 'Configuración',
    'calc.screen': 'Screen/Mosquitero',
    
    // Frame Colors (simplified)
    'calc.white_2605': 'Blanco',
    'calc.gray_2605': 'Gris',
    'calc.black_matte': 'Negro',
    'calc.bronze_2605': 'Bronce',
    
    // Glass Types
    'calc.clear_laminated': 'Vidrio Laminado',
    'calc.insulated_laminated': 'Vidrio Laminado Insulado',
    
    // Reset button
    'calc.reset': 'Reiniciar',
    
    // Glass Tint Categories
    'calc.tintBasic': 'Básicos',
    'calc.tintGreen': 'Tonos Verdes',
    'calc.tintBlue': 'Tonos Azules',
    'calc.tintSpecial': 'Especiales',
    
    // Glass Tints
    'calc.clear': 'Claro',
    'calc.gray': 'Gris',
    'calc.bronze_tint': 'Bronce',
    'calc.solex_green': 'Verde Solex',
    'calc.blue_green': 'Azul-Verde',
    'calc.azuria': 'Azuria',
    'calc.solar_blue': 'Azul Solar',
    'calc.artic_blue': 'Azul Ártico',
    'calc.pacific_blue': 'Azul Pacífico',
    'calc.pacifica_blue': 'Azul Pacifica',
    'calc.solar_cool_gray': 'Gris Solar Cool',
    'calc.solar_cool_bronze': 'Bronce Solar Cool',
    'calc.double_gray': 'Gris Doble',
    'calc.double_bronze': 'Bronce Doble',
    'calc.gray_lite_ii': 'Gris Lite II',
    'calc.solarcool_azuria': 'Solarcool Azuria',
    'calc.solarcool_pacifica': 'Solarcool Pacifica',
    
    // Low-E Options
    'calc.none': 'Ninguno',
    'calc.clima_guard_62_27': 'Clima Guard 62/27',
    'calc.sb70': 'SB70',
    'calc.sb60': 'SB60',
    
    // Actions
    'calc.yes': 'Sí',
    'calc.no': 'No',
    'calc.addProduct': 'Agregar Producto',
    'calc.yourProducts': 'Tus Productos',
    'calc.noProducts': 'No hay productos agregados',
    'calc.remove': 'Eliminar',
    'calc.estimatedTotal': 'Total Estimado',
    'calc.priceRange': 'Rango de Precio Estimado',
    'calc.disclaimer': 'Este es un estimado aproximado basado en configuraciones estándar. El precio final puede variar según disponibilidad, promociones actuales y especificaciones exactas. Llámenos para una cotización oficial sin compromiso.',
    'calc.callForFinal': 'Llamar para Cotización Oficial',
    'calc.startOver': 'Comenzar de Nuevo',
    'calc.close': 'Cerrar',
    'calc.next': 'Siguiente',
    'calc.back': 'Atrás',
    'calc.sqft': 'pies²',
    'calc.each': 'c/u',
    'calc.saveEstimate': 'Guardar Estimado',
    
    // Save Estimate Modal
    'estimate.saveTitle': 'Guardar Tu Estimado',
    'estimate.savedTitle': '¡Estimado Guardado!',
    'estimate.saveDesc': 'Ingresa tu información para guardar tu estimado y recibir una cotización personalizada.',
    'estimate.fullName': 'Nombre Completo',
    'estimate.fullNamePlaceholder': 'Juan Pérez',
    'estimate.email': 'Correo Electrónico',
    'estimate.emailPlaceholder': 'tu@correo.com',
    'estimate.phone': 'Teléfono (opcional)',
    'estimate.phonePlaceholder': '+1 555 123 4567',
    'estimate.yourEstimate': 'Tu Estimado',
    'estimate.products': 'productos',
    'estimate.cancel': 'Cancelar',
    'estimate.save': 'Guardar y Enviar',
    'estimate.savedMessage': '¡Tu estimado ha sido guardado!',
    'estimate.savedSubtitle': 'Te contactaremos pronto. También puedes contactarnos directamente:',
    'estimate.sendWhatsApp': 'Enviar por WhatsApp',
    'estimate.callNow': 'Llamar Ahora',
    'estimate.success.title': '¡Estimado Guardado!',
    'estimate.success.desc': 'Te contactaremos pronto con tu cotización personalizada.',
    'estimate.error.title': 'Error',
    'estimate.error.desc': 'No se pudo guardar el estimado. Por favor intenta de nuevo.',
    'estimate.error.invalidEmail': 'Por favor ingresa un email válido.',
    'estimate.error.invalidPhone': 'Por favor ingresa un teléfono válido.',
    'auth.loginTitle': 'Acceso Admin',
    'auth.loginSubtitle': 'Inicia sesión para acceder al panel de administración',
    'auth.signupTitle': 'Crear Cuenta',
    'auth.signupSubtitle': 'Regístrate para acceder a las funciones de admin',
    'auth.email': 'Correo Electrónico',
    'auth.emailPlaceholder': 'tu@correo.com',
    'auth.password': 'Contraseña',
    'auth.passwordPlaceholder': 'Ingresa tu contraseña',
    'auth.fullName': 'Nombre Completo',
    'auth.fullNamePlaceholder': 'Juan Pérez',
    'auth.loginButton': 'Iniciar Sesión',
    'auth.signupButton': 'Crear Cuenta',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.hasAccount': '¿Ya tienes cuenta?',
    'auth.signupLink': 'Regístrate',
    'auth.loginLink': 'Inicia sesión',
    'auth.backHome': 'Volver al Inicio',
    'auth.error.title': 'Error',
    'auth.error.generic': 'Ocurrió un error. Por favor intenta de nuevo.',
    'auth.error.invalidCredentials': 'Correo o contraseña inválidos.',
    'auth.error.emailNotConfirmed': 'Por favor confirma tu correo antes de iniciar sesión.',
    'auth.error.alreadyRegistered': 'Este correo ya está registrado.',
    'auth.success.loginTitle': '¡Bienvenido!',
    'auth.success.loginDesc': 'Has iniciado sesión exitosamente.',
    'auth.success.signupTitle': '¡Cuenta Creada!',
    'auth.success.signupDesc': 'Tu cuenta ha sido creada. Ahora puedes iniciar sesión.',
    
    // Admin
    'admin.title': 'Panel de Admin',
    'admin.logout': 'Cerrar Sesión',
    'admin.welcome': 'Bienvenido al Panel de Admin',
    'admin.welcomeDesc': 'Administra tus leads, ve estimados y sigue tu negocio.',
    'admin.quickActions': 'Acciones Rápidas',
    'admin.dashboard': 'Dashboard',
    'admin.dashboardDesc': 'Ver estadísticas y métricas',
    'admin.leads': 'Leads',
    'admin.leadsDesc': 'Administrar contactos de clientes',
    'admin.estimates': 'Estimados',
    'admin.estimatesDesc': 'Ver estimados enviados',
    'admin.comingSoon': 'Próximamente',
    'admin.note': 'Nota',
    'admin.noteDesc': 'Las funciones del CRM están en desarrollo. Vuelve pronto para administrar leads y ver estimados.',
    'admin.home': 'Inicio',
    'admin.soon': 'Pronto',
    'footer.adminLogin': 'Admin',
    
    // CRM
    'crm.leadsTitle': 'Gestión de Leads',
    'crm.leadsSubtitle': 'Ver y administrar todos tus leads de clientes',
    'crm.refresh': 'Actualizar',
    'crm.searchPlaceholder': 'Buscar por nombre, email o teléfono...',
    'crm.loading': 'Cargando leads...',
    'crm.noLeads': 'No hay leads aún',
    'crm.noLeadsDesc': 'Los leads aparecerán aquí cuando los clientes envíen su información.',
    'crm.noResults': 'Sin resultados',
    'crm.noResultsDesc': 'Intenta ajustar tu búsqueda o filtros.',
    'crm.call': 'Llamar',
    'crm.showMore': 'Mostrar más opciones',
    'crm.showLess': 'Mostrar menos',
    'crm.changeStatus': 'Cambiar Estado',
    'crm.addNotes': 'Agregar Notas',
    'crm.editNotes': 'Editar Notas',
    'crm.linkedEstimates': 'Estimados Vinculados',
    'crm.products': 'productos',
    'crm.view': 'Ver',
    'crm.source': 'Fuente',
    'crm.notesFor': 'Notas para',
    'crm.notesPlaceholder': 'Agregar notas sobre este lead... (ej: detalles de conversación, recordatorios, solicitudes especiales)',
    'crm.notesHint': 'Las notas son privadas y solo visibles para admins.',
    'crm.cancel': 'Cancelar',
    'crm.saveNotes': 'Guardar Notas',
    'crm.filter.all': 'Todos',
    'crm.filter.new': 'Nuevos',
    'crm.filter.contacted': 'Contactados',
    'crm.filter.negotiating': 'Negociando',
    'crm.filter.won': 'Ganados',
    'crm.filter.lost': 'Perdidos',
    'crm.status.new': 'Nuevo',
    'crm.status.contacted': 'Contactado',
    'crm.status.negotiating': 'Negociando',
    'crm.status.won': 'Ganado',
    'crm.status.lost': 'Perdido',
    'crm.error.fetchTitle': 'Error cargando leads',
    'crm.error.fetchDesc': 'No se pudieron cargar los leads. Intenta de nuevo.',
    'crm.error.updateTitle': 'Error actualizando',
    'crm.error.updateDesc': 'No se pudieron guardar los cambios. Intenta de nuevo.',
    'crm.success.statusTitle': 'Estado actualizado',
    'crm.success.statusDesc': 'El estado del lead ha sido cambiado.',
    'crm.success.notesTitle': 'Notas guardadas',
    'crm.success.notesDesc': 'Tus notas han sido guardadas.',
    
    // Lead Capture
    'lead.title': 'OBTÉN UN ESTIMADO GRATIS',
    'lead.subtitle': 'Ingresa tu email y te contactaremos con una cotización personalizada para tu proyecto.',
    'lead.emailPlaceholder': 'Ingresa tu email',
    'lead.submit': 'Obtener Cotización',
    'lead.sent': '¡Enviado!',
    'lead.success.title': '¡Solicitud Recibida!',
    'lead.success.desc': 'Te contactaremos pronto con tu estimado.',
    'lead.success.message': '¡Gracias! Nos pondremos en contacto pronto.',
    'lead.error.invalidEmail': 'Por favor ingresa un email válido.',
    'lead.error.duplicate': 'Este email ya está registrado. ¡Te contactaremos pronto!',
    'lead.error.generic': 'Algo salió mal. Por favor intenta de nuevo.',
    'lead.privacy': 'Respetamos tu privacidad. Sin spam, nunca.',
    
    // WhatsApp Button
    'whatsapp.button': 'Chatea con Nosotros',
    'whatsapp.aria': 'Contáctanos por WhatsApp',
    'whatsapp.defaultMessage': '¡Hola! Estoy interesado en ventanas y puertas de impacto. ¿Pueden ayudarme?',
    
    // Dashboard
    'dashboard.totalLeads': 'Total de Leads',
    'dashboard.estimates': 'Estimados',
    'dashboard.wonDeals': 'Ventas Ganadas',
    'dashboard.conversion': 'Conversión',
    'dashboard.leadsByStatus': 'Leads por Estado',
    'dashboard.totalRevenue': 'Ingresos Totales',
    'dashboard.revenueDesc': 'Suma de todos los estimados enviados',
    'dashboard.recentLeads': 'Leads Recientes',
    
    // Estimates List
    'estimates.title': 'Estimados',
    'estimates.subtitle': 'Ver todos los estimados enviados',
    'estimates.searchPlaceholder': 'Buscar por nombre o email...',
    'estimates.noEstimates': 'No hay estimados aún',
    'estimates.noEstimatesDesc': 'Los estimados aparecerán aquí cuando los clientes los envíen.',
    'estimates.anonymous': 'Anónimo',
    'estimates.taxIncluded': 'Impuesto incluido',
    'estimates.contactInfo': 'Información de Contacto',
    'estimates.product': 'Producto',
    'estimates.dimensions': 'Dimensiones',
    'estimates.options': 'Opciones',
    'estimates.price': 'Precio',
    'estimates.subtotal': 'Subtotal',
    'estimates.taxes': 'Impuestos',
    'estimates.total': 'Total',
    'estimates.exportPDF': 'Exportar PDF',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    // Fallback for HMR edge cases — prevents blank screen
    return {
      language: 'es',
      setLanguage: () => {},
      t: (key: string) => key,
    };
  }
  return context;
};
